molgenis/molgenis-frontend

- packages/core-ui/src/modules/react-components/jobs/Job.js
Ports https://github.com/molgenis/molgenis/pull/8222 to frontend repository.
> fix(core-ui): Fix job cancel when used through job overview plugin

- preset.json
> no class components in default template

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- package.json
- yarn.lock
> [CHORE] Describe and support the use of conventional commits

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
> [CHORE] Updated readme

- README.md
- packages/menu/package.json
> Document usage of yarn link

- packages/settings/package.json
- packages/settings/src/main.js
- packages/settings/yarn.lock
> Bump molgenis dev deps + fix i18n import issue

- lerna.json
> chore(lerna.json) Add frozen lockfile option to yarn install phase

- packages/searchall/src/store/actions.js
- packages/searchall/test/unit/specs/actions.spec.js
- packages/security/src/store/actions.js
- packages/security/test/unit/specs/store/actions.spec.js
> Update searchAll and security endpoints

- packages/metadata-manager/src/components/MetadataManagerAttributeEditForm.vue
see the issue for details on the typos fixed 
fixes issue #8157
> fix(metadata-manager): implement bootstrap checkbox guidelines

- packages/data-row-edit/LICENSE
- packages/data-row-edit/package.json
- packages/data-row-edit/src/repository/dataRowRepository.js
- packages/data-row-edit/test/unit/specs/repository/dataRowRepository.spec.js
- packages/metadata-manager/src/components/MetadataManagerAttributeEditForm.vue
> fix(data-row-edit): check for empty file value

- packages/scripts/src/components/CodeEditor.vue
- packages/scripts/src/service/parameterService.ts
- packages/scripts/src/types/state.ts
- packages/scripts/src/views/EditScript.vue
- packages/scripts/src/views/NewScript.vue
- packages/scripts/tests/unit/components/CodeEditor.spec.js
- packages/scripts/tests/unit/service/parameterService.spec.ts
> fix(scripts): fix #8384 use different extractor based on script type

- Jenkinsfile
> [CHORE] publish PR previews

- Jenkinsfile
* Use good old curl to post the comment instead of the github jenkins plugin
* Only put up preview for PRs
> ci: post comment with the PR url

- Jenkinsfile
> chore: upgrade to rancher 2.2

- packages/scripts/src/views/EditScript.vue
- packages/scripts/src/views/NewScript.vue
> fix(scripts): remove type=submit from non-form buttons

- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
- packages/scripts/package.json
- packages/scripts/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
Fix for nullable expression error
fix #8470
> fix(data-row-edit): Fix for #8470 and #8464

- packages/menu/package.json
- packages/menu/yarn.lock
> [FIX] #8486 hamburger always displayed ie11

- packages/menu/package.json
- packages/menu/yarn.lock
> fix(menu): Fix 8300 error in console when not signed in

- packages/settings/package.json
- packages/settings/yarn.lock
> fix(settings): 8520 bump molgenis-ui-form 4.0.0 -> 4.0.1 in settings

- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
> fix(data-row-edit): bump molgenis-ui-form 4.0.0 -> 4.0.1

- packages/core-ui/webpack.production.config.js
> feature(core-ui): add build info to core ui webpack build artifacts

- README.md
- TROUBLESHOOTING.md
> [CHORE] Updated README based upon comments from devs

- Jenkinsfile
- lerna.json
> chore: specify publish registry

- Jenkinsfile
> chore: write NPM_TOKEN to .npmrc

- README.md
> [DOCS] deployment and release strategy

- Jenkinsfile
> fix(Jenkinsfile): point to right proxy-url

- Jenkinsfile
- packages/menu/yarn.lock
> fix: removed broken dependency

- Jenkinsfile
> ci(docker auth): fixed way of authenticating against dockerhub

- Jenkinsfile
Reverts molgenis/molgenis-frontend#85
> Revert "ci(docker auth): fixed way of authenticating against dockerhub"

- README.md
- packages/data-explorer/jest.config.js
- packages/data-explorer/nightwatch.config.js
- packages/data-explorer/package.json
- packages/data-explorer/public/index.html
- packages/data-explorer/src/App.vue
- packages/data-explorer/src/main.ts
- packages/data-explorer/src/views/FiltersView.vue
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/tests/unit/App.spec.ts
- packages/data-explorer/vue.config.js
- packages/data-explorer/yarn.lock
> Add filters

- packages/data-explorer/package.json
- packages/data-explorer/src/App.vue
- packages/data-explorer/src/main.ts
- packages/data-explorer/src/router.ts
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/yarn.lock
> feat(data-explorer): Add router

- docker/proxy-config/proxy.d/common.conf
> fix(proxy): drop routing information from url

- Jenkinsfile
> ci(Jenkinsfile): updated keys for resolving within cluster

- packages/scripts/src/views/ListScripts.vue
- packages/scripts/tests/test-schemas.js
- packages/scripts/vue.config.js
Fixes: https://github.com/molgenis/molgenis/issues/8380
Fixes e2e test being to slow without a molgenis instance running in the background
> fix(Scripts): Remove tooltip

- packages/data-explorer/package.json
- packages/data-explorer/vue.config.js
- packages/data-explorer/yarn.lock
> chore(buildpath): fix buildpath dataexplorer and added banner

- packages/data-explorer/src/router.ts
> fix(router): updated base path

- packages/data-row-edit/package.json
> chore(package.json): Set index.html to main to be able to use on unpkg

- packages/data-explorer/src/components/Utils/TableSettingsButton.vue
- packages/data-explorer/src/store/actions.ts
- packages/data-explorer/src/store/mutations.ts
- packages/data-explorer/src/store/state.ts
- packages/data-explorer/src/types/ApplicationState.ts
- packages/data-explorer/src/views/DataView.vue
- packages/data-explorer/tests/unit/components/Utils/TableSettingsButton.spec.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
- packages/data-explorer/tests/unit/store/mutations.spec.ts
- packages/data-explorer/tests/unit/views/DataView.spec.ts
> feat(settings): Read settings from settings table

- packages/data-explorer/src/store/actions.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
- packages/data-explorer/vue.config.js
> fix(vue.config): Update config to work with new backend

- packages/data-explorer/src/repository/metaDataRepository.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
> task(data-explorer): improve performance, fetch metaData without data.

- packages/data-explorer/src/views/TableView.vue
- packages/data-explorer/tests/unit/views/TableView.spec.ts
> fix(data-explorer): fixed broken table after internal data change

- packages/data-explorer/src/views/ClipboardView.vue
- packages/data-explorer/src/views/DataView.vue
> fix(data-explorer): Fixed broken clipboard

- packages/data-explorer/src/store/mutations.ts
- packages/data-explorer/src/store/state.ts
- packages/data-explorer/src/types/ApplicationState.ts
- packages/data-explorer/src/views/CardView.vue
- packages/data-explorer/src/views/ClipboardView.vue
- packages/data-explorer/src/views/EntityView.vue
- packages/data-explorer/src/views/FiltersView.vue
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/tests/unit/store/actions.spec.ts
- packages/data-explorer/tests/unit/store/mutations.spec.ts
- packages/data-explorer/tests/unit/views/FiltersView.spec.ts
- packages/data-explorer/tests/unit/views/MainView.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
Reason: Value was flipped from what you would expect from naming
> fix(data-explorer): Changed naming

- packages/data-explorer/public/index.html
> fix(data-explorer): Added the correct url to molgenis bootstrap style

- packages/data-explorer/CHANGELOG.md
- packages/data-explorer/package.json
- packages/data-explorer/src/components/dataView/DefaultCardContent.vue
- packages/data-explorer/src/components/dataView/ExplorerCard.vue
- packages/data-explorer/src/components/utils/ShoppingButton.vue
- packages/data-explorer/src/repository/dataRepository.ts
- packages/data-explorer/src/repository/metaDataRepository.ts
- packages/data-explorer/src/store/actions.ts
- packages/data-explorer/src/store/mutations.ts
- packages/data-explorer/src/store/state.ts
- packages/data-explorer/src/types/ApiResponse.ts
- packages/data-explorer/src/types/ApplicationState.ts
- packages/data-explorer/src/views/CardView.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/tests/unit/components/dataView/ExplorerCard.spec.ts
- packages/data-explorer/tests/unit/repository/metaDataRepository.spec.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
- packages/data-explorer/tests/unit/store/mutations.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
- packages/data-explorer/vue.config.js
- Add expand button to card
- Add fetch row data action
- Update store dataTable with expanded row
- Add link to detail view
> feat(data-explorer): expandable card

- Jenkinsfile
> chore(e2e): added e2e configuration for ci

- packages/data-explorer/tests/e2e/specs/test.js
> task(data-explorer): fix e2e test

- Jenkinsfile
> chore: added e2e to master build as well

- packages/app-manager/src/pages/AppManagerContainer.vue
> fix(app-manager): add noreferrer to link

- packages/metadata-manager/src/store/actions.js
Only join message parts with colon is parts exist
FIX: #123
> fix(metadata-manager): fix 8468

- packages/data-explorer/vue.config.js
Login cookie is stored cross domain
> feat(data-explorer): Fix login

- docker/preview-config/proxy.d/backend.conf
- docker/proxy-config/proxy.d/backend.conf
Allow big requests to the backend
> chore: fix backend max body size

- docker/proxy-config/proxy.d/frontend/lts.conf
If I understand it correctly, the lts is what we're going to test and release.
Updating the versions to latest and greatest.
> chore: update lts versions

- docker/proxy-config/proxy.d/frontend/lts.conf
> chore: update lts config

- Jenkinsfile
- README.md
> chore(Jenkinsfile): fetch target branch for PR

- .vscode/settings.json
- packages/data-row-edit/src/components/DataRowEdit.vue
- packages/metadata-manager/src/components/MetadataManagerAttributeEditForm.vue
- packages/metadata-manager/src/components/MetadataManagerEntityEditForm.vue
- packages/metadata-manager/src/components/MetadataManagerHeader.vue
- packages/metadata-manager/src/components/generic-components/AttributeTreeNode.vue
- packages/metadata-manager/src/components/generic-components/Spinner.vue
- packages/navigator/src/components/NavigatorBreadcrumb.vue
> [FIX] fix a couple of sonar warnings

- Jenkinsfile
- packages/data-explorer/src/repository/dataRepository.ts
- packages/data-explorer/src/repository/queryBuilder.ts
- packages/data-explorer/src/store/actions.ts
- packages/data-explorer/src/store/getters.ts
- packages/data-explorer/src/store/store.ts
- packages/data-explorer/tests/unit/repository/dataRepository.spec.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
Note: rsql from getter is mocked for now, edit in getters.ts to test
> feat(data-explorer): add rsql filter to data request if set

- packages/data-explorer/tests/e2e/specs/test.js
> test(data-explorer): Update e2e test URLs

- packages/components/package.json
> fix(components): Fix publish setup, remove double publish access.

- packages/components/README.md
> feat(components): Add note on usage to readme

- Jenkinsfile
- packages/data-explorer/package.json
- packages/data-explorer/src/components/dataView/DefaultCardContent.vue
- packages/data-explorer/src/components/dataView/ExplorerCard.vue
- packages/data-explorer/tests/unit/components/dataView/DefaultCardContent.spec.ts
- packages/data-explorer/yarn.lock
> Revert moving DefaultCardData to separate component ( Due to CI cache issue) 

- packages/data-explorer/src/components/utils/TableSettingsButton.vue
- packages/data-explorer/src/views/DataView.vue
- packages/data-explorer/tests/unit/components/utils/TableSettingsButton.spec.ts
> feat(data-explorer): Linkup tableSettings btn with data-row edit plugin

- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/tests/e2e/specs/test.js
- packages/data-explorer/tests/unit/views/MainView.spec.ts
> fix(SideBar): Fix sidebar button

- packages/components/public/index.html
- packages/components/src/App.vue
- packages/components/src/components/ToastComponent.vue
- packages/components/src/components/index.ts
- packages/components/tests/unit/components/ToastComponent.spec.ts
- Add toast component
- Add bootstrap to demo page
> feat(components): Add toast component

- packages/metadata-manager/src/store/mutations.js
fixes https://github.com/molgenis/molgenis/issues/8732
> fix(metadata-manager): persist metadata-manager attribute in url

- docker/proxy-config/proxy.d/frontend/lts.conf
> chore: update 8-lts to include fixes

- packages/metadata-manager/src/components/MetadataManagerAttributeEditForm.vue
- packages/metadata-manager/src/store/actions.js
> fix: update isNew property

- Jenkinsfile
> fix: jenkins home dir moved to variable: ${JENKINS_AGENT_WORKDIR}

- Jenkinsfile
> fix: do not update configuration because of preview image

- packages/data-explorer/package.json
- packages/data-explorer/tests/e2e/resources/uiContext.js
- packages/data-explorer/tests/e2e/specs/test.js
- packages/data-explorer/yarn.lock
- packages/legacy-lib/package.json
- packages/legacy-lib/yarn.lock
fix: https://github.com/molgenis/molgenis/issues/8862
> fix: bump version of molgenis-ui-context to fix cookiewall bug

- packages/data-explorer/README.md
> feat: updated readme to reflect how to set env variable

- packages/data-explorer/src/components/SearchComponent.vue
- packages/data-explorer/tests/unit/components/SearchComponent.spec.ts
- Use form instead op button action ( to add keyboard support)
- Use html5 search component ( progressive enhancement ) to add clear search support
- add vue watch handler to react to html5 clear search action
> feat: Improve search ux

- packages/data-explorer/package.json
- packages/data-explorer/yarn.lock
fix(data-explorer): bump @molgenis/molgenis-ui-context from 1.6.3 to 1.6.4
- This fixes issue with duplicate vue keys in submenus ( see @molgenis/molgenis-ui-context 1.6.4 for details)
> fix(data-explorer): bump @molgenis/molgenis-ui-context to 1.6.4

- packages/data-explorer/src/App.vue
- packages/data-explorer/src/main.ts
- Add a the missing bootstrap-vue css.
- Removed a ugly hack
> fix: Add missing bootstrap vue css

- packages/data-explorer/src/components/dataView/TableHeader.vue
- packages/data-explorer/src/components/dataView/TableRow.vue
- packages/data-explorer/src/views/ClipboardView.vue
- packages/data-explorer/src/views/TableView.vue
- packages/data-explorer/tests/unit/components/dataView/TableHeader.spec.ts
- packages/data-explorer/tests/unit/components/dataView/TableRow.spec.ts
- packages/data-explorer/tests/unit/views/ClipboardView.spec.ts
- packages/data-explorer/tests/unit/views/TableView.spec.ts
> feat(data-explorer): 7247 Use metadata for table structure

- packages/data-explorer/src/components/dataView/DefaultCardContent.vue
- packages/data-explorer/src/components/dataView/TableHeader.vue
- packages/data-explorer/src/components/dataView/TableRow.vue
- packages/data-explorer/src/main.ts
- packages/data-explorer/src/repository/dataRepository.ts
- packages/data-explorer/src/store/actions.ts
- packages/data-explorer/src/store/mutations.ts
- packages/data-explorer/src/views/ClipboardView.vue
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/src/views/TableView.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/tests/unit/components/dataView/TableHeader.spec.ts
- packages/data-explorer/tests/unit/components/dataView/TableRow.spec.ts
- packages/data-explorer/tests/unit/repository/dataRepository.spec.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
- packages/data-explorer/tests/unit/store/mutations.spec.ts
- packages/data-explorer/tests/unit/views/MainView.spec.ts
- packages/data-explorer/tests/unit/views/TableView.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
- packages/data-explorer/vue.config.js
- Add button with link to data-row-edit plugin
- Do not show button in cart view
> Add create, delete and edit card/row controls

- packages/data-explorer/package.json
- packages/data-explorer/src/mappers/rsqlMapper.ts
- packages/data-explorer/tests/unit/mappers/rsqlMapper.spec.ts
- packages/data-explorer/yarn.lock
> feat: Add greater and lesser rsql mapping for rangefilter and version bump

- packages/data-explorer/package.json
- packages/data-explorer/yarn.lock
> fix: ui-filters version bump

- docker/proxy-config/proxy.d/frontend/lts.conf
Bump from data-row-edit version from 3.0.3 to 3.0.5 in lts config
> task: bump data-row-edit

- packages/data-explorer/tests/unit/repository/dataRepository.spec.ts
- packages/data-explorer/tests/unit/repository/queryBuilder.spec.ts
- Cleanup test; mock dependacy
> feat(data-explorer): trigger release

- packages/data-explorer/src/components/SearchComponent.vue
- packages/data-explorer/src/mappers/bookmarkMapper.ts
- packages/data-explorer/src/mappers/rsqlMapper.ts
- packages/data-explorer/src/store/mutations.ts
- packages/data-explorer/src/store/state.ts
- packages/data-explorer/src/types/ApplicationState.ts
- packages/data-explorer/src/views/FiltersView.vue
- packages/data-explorer/tests/unit/components/SearchComponent.spec.ts
- packages/data-explorer/tests/unit/mappers/bookmarkMapper.spec.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
- packages/data-explorer/tests/unit/store/mutations.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
> fix: add search to bookmark

- packages/data-explorer/tests/unit/components/SearchComponent.spec.ts
- packages/data-explorer/tests/unit/components/utils/TableSettingsButton.spec.ts
- packages/data-explorer/tests/unit/mocks/mockState.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
- packages/data-explorer/tests/unit/store/mutations.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
> fix: refactored unittests

- packages/app-manager/src/pages/AppManagerContainer.vue
- change books to book
- update ref to more relevant section
Closes #309
> fix(app-manager): Update link to docs

- packages/data-explorer/tests/unit/views/MainView.spec.ts
> fix: flaky test

- packages/data-explorer/src/lib/api.ts
- packages/data-explorer/src/lib/client.ts
- packages/data-explorer/src/mappers/utils.ts
- packages/data-explorer/src/repository/dataRepository.ts
- packages/data-explorer/src/repository/metaDataRepository.ts
- packages/data-explorer/src/store/actions.ts
- packages/data-explorer/src/store/header/actions.ts
- packages/data-explorer/tests/unit/mappers/utils.spec.ts
- packages/data-explorer/tests/unit/repository/dataRepository.spec.ts
- packages/data-explorer/tests/unit/repository/metaDataRepository.spec.ts
- packages/data-explorer/tests/unit/store/header/actions.spec.ts
> fix: redirect to login page on 401

- packages/data-explorer/src/store/actions.ts
> fix: data response table settings

- packages/data-explorer/src/store/actions.ts
- packages/data-explorer/src/store/state.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
- packages/data-explorer/vue.config.js
- Change default settings location
- Add test for settings location
- Fix no-op test
Do not merge yet: blocked by https://github.com/molgenis/molgenis/pull/9029
> feat(data-explorer): Use sys table settings

- packages/data-explorer/src/store/state.ts
- packages/data-explorer/tests/unit/store/actions.spec.ts
- packages/data-explorer/vue.config.js
> fix: reverted pre-emptive systable merge

- packages/navigator/src/components/NavigatorTable.vue
> feat: Use experimental data explorer url

- packages/data-explorer/package.json
- packages/data-explorer/src/mappers/rsqlMapper.ts
- packages/data-explorer/tests/unit/components/__snapshots__/TableSelect.spec.ts.snap
- packages/data-explorer/tests/unit/mappers/rsqlMapper.spec.ts
> fix: make lesser equal query work

- packages/data-explorer/src/App.vue
- packages/data-explorer/src/components/dataView/DefaultCardContent.vue
- packages/data-explorer/src/components/dataView/ExplorerCard.vue
- packages/data-explorer/src/components/dataView/TableRow.vue
- packages/data-explorer/src/store/getters.ts
- packages/data-explorer/src/store/store.ts
- packages/data-explorer/src/views/CardView.vue
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/src/views/TableView.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/tests/unit/store/getters.spec.ts
- packages/data-explorer/tests/unit/views/MainView.spec.ts
- packages/data-explorer/tests/unit/views/TableView.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
- load context via ui-context component
- add account module to store
- use account module in getters hasEditRights flag
- pass flag to components to toggle edit mode
> feat(data-explorer): Hide/Show edit mode via context

- packages/data-explorer/package.json
- packages/data-explorer/yarn.lock
> fix(data-explorer): updated ui-filter package to 1.11.1

- packages/data-explorer/src/store/getters.ts
- packages/data-explorer/src/views/PageHeaderView.vue
- packages/data-explorer/tests/unit/store/getters.spec.ts
- packages/data-explorer/tests/unit/views/PageHeaderView.spec.ts
- Only show edit table settings btn for super user
- Refacor getters for better code reuse
> feat(data-explorer): Hide / Show edit table settings btn

- docker/proxy-config/proxy.d/backend.conf
> chore(docker): configure proxy_read_timeout

- packages/data-explorer/src/lib/bootstrapExplorer.ts
- packages/data-explorer/tests/unit/lib/bootstrapExplorer.spec.ts
> fix(data-explorer): Fix bootstrapper unit test

- Jenkinsfile
- packages/data-explorer/package.json
> fix(data-explorer): move data-explorer registry to molgenis-ui

- packages/navigator/src/components/NavigatorTable.vue
use molgenis-ui instead of molgenis-experimental
> task(navigator): update link to data-explorer 2 

- docker/proxy-config/proxy.d/frontend/lts.conf
- docker/proxy-config/proxy.d/frontend/stable.conf
> chore(docker): specify data explorer versions

- packages/security/src/store/actions.ts
- packages/security/src/store/getters.ts
- packages/security/tests/unit/store/actions.spec.ts
> fix(security): #336 Changing Security permission fails with unknown entity exception

- packages/security/src/components/GroupDetail.vue
> feat(security): improve layout

- packages/data-row-edit/src/components/DataRowEdit.vue
- Innocent until proven guilty
Closes #207
> fix(data-row-edit): only display errors after saving incorrect data

- packages/data-explorer/src/views/PageHeaderView.vue
> fix: pass correct props to TableSettingsButton component

- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
- packages/scripts/package.json
- packages/scripts/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
Use 5.x version of @molgenis/molgenis-ui-form
Closes  #346
breaking changes: i18n key 'ui-form:form_not_a_valid_url' replaced with to 'ui-form:form_not_a_valid_hyperlink'
> fix(settings, data-row-edit, questionnaire, scripts): Update forms

- Jenkinsfile
On PR success build try to remove the previous pr-preview before setting up the new pr-preview
> Remove old preview if exists

- Jenkinsfile
> task: fix delete script, use NAME instead of TAG

- Jenkinsfile
- packages/settings/tests/unit/SettingsUi.spec.ts
> fix(settings): fixed TS typting for unittest

- sonar-project.properties
Update lcov locations for sonar to user
packages setup ( or updated) with vue cli 4 use new coverage location
> task: Update sonar config

- package.json
- yarn.lock
> chore: removed unnecessary package

- packages/components-library/src/main.ts
> fix(components-library): now exposes correctly

- packages/data-explorer/src/views/EntityView.vue
- packages/data-explorer/tests/unit/views/CardView.spec.ts
- packages/data-explorer/tests/unit/views/TableView.spec.ts
( ClipboardView.vue is the current solution. )
Note: review point of interest
I don't even think Entity you can get to EntityView.vue?
> chore: Removed remnants of deprecated "shoppingFilter" from code.

- packages/components-library/src/components/CartSelectionToast.vue
- packages/components-library/tests/unit/CartSelectionToast.spec.ts
> feat(components-library): Allow object data in CartSelectionToast

- packages/components-library/src/components/filters/StringFilter.vue
- packages/components-library/src/main.ts
- packages/components-library/tests/unit/filters/CheckboxFilter.spec.ts
- packages/components-library/tests/unit/filters/StringFilter.spec.ts
- packages/components-library/tests/unit/filters/__snapshots__/StringFilter.spec.ts.snap
- packages/components-library/tests/unit/ui/CartSelectionToast.spec.ts
- Move String filter over from filter repo to component repo
- Extend test to cover missing cases
- Fix lint issues
- Add StringFilter to build uitput
> feat(components-library): Add string-filter component

- packages/security/package.json
- packages/security/public/index.html
- packages/security/src/SecurityApp.vue
- packages/security/src/components/GroupDetail.vue
- packages/security/src/components/GroupOverview.vue
- packages/security/src/main.ts
- packages/security/src/store/getters.ts
- packages/security/src/store/index.ts
- packages/security/src/store/mutations.ts
- packages/security/src/types/LoginUser.ts
- packages/security/src/types/SecurityModel.ts
- packages/security/tests/unit/components/GroupCreate.spec.ts
- packages/security/tests/unit/components/GroupDetail.spec.ts
- packages/security/tests/unit/components/GroupOverview.spec.ts
- packages/security/tests/unit/store/getters.spec.ts
- packages/security/tests/unit/store/mutations.spec.ts
- packages/security/vue.config.js
- packages/security/yarn.lock
> fix(security): fixes #352 - console errors

- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
fix: Version bump to use the latest forms lib for additional error messages
> fix: forms version bump

- README.md
This one has more useful information and is less distractingly huge
> docs: replace sonatype badge

- docker/proxy-config/proxy.d/frontend/lts.conf
> feat(release): updated lts config with the latest stable frontend packages

- docker/proxy-config/proxy.d/frontend/stable.conf
> fix(stable-conf): updated major version in stable conf

- packages/components-library/babel.config.js
- packages/components-library/package.json
- packages/components-library/rollup.config.js
- packages/components-library/yarn.lock
> feat: add babel to rollup build for components lib

- packages/data-explorer/tests/unit/components/utils/TableSettingsButton.spec.ts
> chore: fix test warning

- Jenkinsfile
> chore(data-explorer): force node module update

- packages/data-explorer/jest.config.js
> chore(data-explorer): Use explicit jest module path

- Jenkinsfile
> fix: Fix master build by building lib before test usage

- Jenkinsfile
- packages/data-explorer/vue.config.js
> Fix data-explorer e2e test build by not following symlinks 

- Jenkinsfile
- packages/components-library/README.md
- packages/components-library/src/components/filters/containers/FilterCard.vue
> feat: add custom css class for header

- packages/components-library/src/components/filters/CheckboxFilter.vue
> fix(components-library): removed computed in favour of v-model

- packages/components-library/src/components/filters/CheckboxFilter.vue
> fix(components-library): fixed infinite loop sometimes occurring

- packages/components-library/src/components/filters/CheckboxFilter.vue
- packages/components-library/tests/unit/filters/CheckboxFilter.spec.ts
- Functionality works & meets specifications
> fix(components-library): Fixed naming convention

- packages/components-library/src/components/filters/CheckboxFilter.vue
- packages/components-library/src/components/filters/MultiFilter.vue
> fix(components-library): deduplicate options when fetching based on initial value

- packages/components-library/src/components/filters/MultiFilter.vue
for correct responsiveness of v-model of checkbox group
> fix(components-library): Object assign is really required

- doc/adr/0004-molgenis-core-apps.md
> chore: #7309 add molgenis core apps adr

- packages/components-library/package.json
- packages/components-library/rollup.config.js
- packages/components-library/src/components/ui/Toaster.vue
- packages/components-library/src/main.ts
- packages/components-library/src/types/Toast.ts
- packages/components-library/tests/unit/ui/Toaster.spec.ts
> feat: add Toaster component

- Jenkinsfile
- packages/data-row-edit/src/components/DataRowEdit.vue
- packages/data-row-edit/tests/unit/components/DataRowEdit.spec.ts
- Add handler for different errors types
closes #209
> fix(data-row-edit): Fix showing server side error

- docker/proxy-config/proxy.d/frontend/lts.conf
> task: dump data-row-edit version, fixes molgenis issue #9123

- docker/proxy-config/proxy.d/frontend/lts.conf
> chore: Bump proxy lts config to include bug fix

- packages/data-explorer/src/lib/client.ts
- packages/data-explorer/tests/unit/lib/client.spec.ts
- set timeout to 0 to keep error notification from disappearing
closes #461
> fix(data-explorer): Fix 461 Errors in the dataexplorer disappear

- doc/adr/0005-index-file-delivery.md
> chore: add index file adr

- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
- packages/scripts/package.json
- packages/scripts/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
to add display for validator error
> feat(data-row-edit, settings, questionnaires): version bump 

- packages/components-library/README.md
> fix(components-library): bump release

- packages/scripts/src/service/parameterService.ts
- packages/scripts/tests/unit/service/parameterService.spec.ts
> fix(scripts): add _ to parameter regex

- packages/components-library/src/components/ui/Pagination.vue
- packages/components-library/src/types/Pagination.ts
- packages/components-library/tests/unit/filters/containers/FilterContainer.spec.ts
- packages/components-library/tests/unit/ui/Pagination.spec.ts
Component part of pagination story
> fix(components-library): fix pagination issues + lint code

- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
- packages/scripts/package.json
- packages/scripts/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
> fix: Upgrade forms to 5.2.1

- docker/proxy-config/proxy.d/frontend/lts.conf
- docker/proxy-config/proxy.d/frontend/stable.conf
> chore: bump versions for release 8.6.0

- Jenkinsfile
> chore: remove e2e tests for Jenkins

- packages/data-explorer/package.json
- packages/data-explorer/yarn.lock
- packages/legacy-lib/package.json
- packages/legacy-lib/yarn.lock
- packages/security/package.json
- packages/security/yarn.lock
> fix: upgrade ui-context

- packages/settings/public/index.html
- packages/settings/src/components/SettingsUi.vue
- packages/settings/vue.config.js
Fixes: https://github.com/molgenis/molgenis-theme/issues/24
> fix: Settings header does not align

- docker/proxy-config/proxy.d/frontend/lts.conf
> fix: bump versions lts for 8.6

- packages/data-explorer/src/views/MainView.vue
> fix(data-explorer): Only show pagination at bottom of page

- docker/proxy-config/proxy.d/frontend/lts.conf
- docker/proxy-config/proxy.d/frontend/stable.conf
> fix: add molgenis-theme pinning to proxy config

- docker/proxy-config/proxy.d/frontend/lts.conf
> fix: bump data explorer 2 in lts.conf

- packages/data-explorer/src/components/dataView/TableHeader.vue
- packages/data-explorer/src/components/dataView/TableRow.vue
- fix table header and first col background color
> fix(data-explorer): table style

- packages/components-library/src/components/ui/Pagination.vue
- Remove hard color from component
- This allows for styling by component user
Closes #507
> fix(components-library): Fix 507 hard color in component

- packages/components-library/src/components/ui/Pagination.vue
- packages/components-library/tests/unit/ui/Pagination.spec.ts
BREAKING CHANGE: Requires consumers to implement Vue-router navigation
> feat(components-library): remove router from Pagination component

- packages/components-library/src/components/ui/Pagination.vue
- packages/components-library/tests/unit/ui/Pagination.spec.ts
Update the model when the size changes
Emit a input event passing the updated model to notify listeners
> fix(components-library): emit updated model on size change

- packages/data-explorer/yarn.lock
> chore(data-explorer): cleanup lock file

- packages/data-explorer/src/components/SortSelect.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/tests/unit/components/SortSelect.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
- Add sortSelect component to enable sort in Card view
> feat(data-explorer): Add sorting for CardView

- packages/components-library/src/components/ui/Pagination.vue
- packages/data-explorer/src/router.ts
- packages/data-explorer/src/store/mutations.ts
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/tests/unit/views/MainView.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
> fix: add view to router & parse page/size to int from router

- packages/data-explorer/src/components/dataDisplayTypes/DataDisplayCell.vue
- packages/data-explorer/src/components/dataDisplayTypes/DateDisplay.vue
- packages/data-explorer/src/components/dataDisplayTypes/EmailDisplay.vue
- packages/data-explorer/src/components/dataDisplayTypes/HTMLDisplay.vue
- packages/data-explorer/src/components/dataDisplayTypes/LinkDisplay.vue
- packages/data-explorer/src/components/dataDisplayTypes/RefDisplay.vue
- packages/data-explorer/src/components/dataDisplayTypes/StringDisplay.vue
- packages/data-explorer/src/components/dataView/TableRow.vue
> fix: improved readability and fixed null check

- packages/data-explorer/src/views/FiltersView.vue
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/src/views/TableView.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/tests/unit/views/TableView.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
- remove path from router push ( name is used, instead of both name and path)
- used fixed name instead of current route name
> chore(data-explorer): Replace dynamic route and remove unused code

- Jenkinsfile
> fix: new tag for jenkins image

- packages/data-explorer/src/components/ColumnSelection.vue
- packages/data-explorer/src/components/dataView/DefaultCardContent.vue
- packages/data-explorer/src/components/dataView/ExplorerCard.vue
- packages/data-explorer/src/main.ts
- packages/data-explorer/src/store/mutations.ts
- packages/data-explorer/src/store/state.ts
- packages/data-explorer/src/types/ApplicationState.ts
- packages/data-explorer/src/types/RouteQuery.ts
- packages/data-explorer/src/views/CardView.vue
- packages/data-explorer/src/views/FiltersView.vue
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/src/views/TableView.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/tests/unit/components/ColumnSelection.spec.ts
- packages/data-explorer/tests/unit/components/dataView/DefaultCardContent.spec.ts
- packages/data-explorer/tests/unit/store/mutations.spec.ts
- packages/data-explorer/tests/unit/views/TableView.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
- Add 'hide' query-param to route type
- Set hiddenColumns on state when set in route
- Hide hidden columns in tableView
- Hide hidden fields in defaultCardView
- Do NOT hide anything in custom cardview
> feat(data-explorer): Allow user to hide columns

- packages/data-explorer/src/components/ColumnSelection.vue
- packages/data-explorer/tests/unit/components/ColumnSelection.spec.ts
> feat: add select / deselect all to show/hide columms

- packages/data-explorer/src/components/SearchComponent.vue
- packages/data-explorer/src/components/dataDisplayTypes/DateDisplay.vue
- packages/data-explorer/src/components/dataDisplayTypes/HTMLDisplay.vue
- packages/data-explorer/src/components/dataDisplayTypes/RefTable.vue
- packages/data-explorer/src/components/dataDisplayTypes/StringDisplay.vue
- packages/data-explorer/src/components/dataView/DefaultCardContent.vue
- packages/data-explorer/src/components/dataView/TableRow.vue
- packages/data-explorer/src/components/utils/TableSettingsButton.vue
- packages/data-explorer/src/views/ClipboardView.vue
- packages/data-explorer/src/views/DataView.vue
- packages/data-explorer/src/views/FiltersView.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/tests/unit/components/SearchComponent.spec.ts
- packages/data-explorer/tests/unit/components/dataView/DefaultCardContent.spec.ts
- packages/data-explorer/tests/unit/components/dataView/TableRow.spec.ts
- packages/data-explorer/tests/unit/components/utils/TableSettingsButton.spec.ts
- packages/data-explorer/tests/unit/views/FiltersView.spec.ts
- packages/data-explorer/tests/unit/views/ToolbarView.spec.ts
- Replace fixed labels with i18n labels
Related to: https://github.com/molgenis/molgenis/pull/9160
> feat(data-explorer): i18n for data explorer 2

- Jenkinsfile
> chore: re-enable e2e tests (for de2)

- Jenkinsfile
> fix: disable e2e test again due to unstable jenkins

- packages/components-library/src/components/filters/MultiFilter.vue
- packages/components-library/src/dev-dependencies.ts
> feat(components-library): changed icon of multifilter to be more informative

- packages/data-explorer/src/components/dataView/DefaultCardContent.vue
- packages/data-explorer/src/store/actions.ts
- packages/data-explorer/src/store/mutations.ts
- packages/data-explorer/src/store/state.ts
- packages/data-explorer/src/types/ApplicationState.ts
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/yarn.lock
> chore(data-explorer): added spinner on dataload

- packages/data-explorer/src/components/utils/TableSettingsButton.vue
- packages/data-explorer/src/views/ToolbarView.vue
- packages/data-explorer/yarn.lock
chore(data-explorer): added media query to help with visibility of the toolbar on small screens
> chore(data-explorer): added media query to help with visibility of the toolbar

- packages/components-library/src/components/filters/containers/FilterContainer.vue
- packages/components-library/src/dev-dependencies.ts
- packages/components-library/tests/unit/filters/containers/FilterContainer.spec.ts
- packages/data-explorer/src/main.ts
- packages/data-explorer/src/views/FiltersView.vue
- packages/data-explorer/tests/unit/lib/client.spec.ts
- packages/data-explorer/tests/unit/repository/metaDataResponseMapper.spec.ts
> fix: use dropdown to change filters; updated styling

- packages/data-explorer/src/views/MainView.vue
> fix: stacking context left sidebar

- packages/core-ui/src/modules/react-components/AggregateTable.js
- packages/core-ui/src/modules/react-components/Table.js
- packages/core-ui/src/modules/react-components/css/Table.css
- packages/core-ui/src/modules/react-components/jobs/JobTable.js
- packages/navigator/src/components/NavigatorTable.vue
> fix: make navigator table bordered by default

- Jenkinsfile
> clear yarn cache on master build

- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
- packages/scripts/package.json
- packages/scripts/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
feat(data-row-edit, questionnaires, scripts, settings)
Bump molgenis-ui-form dep to 5.3.0
- version 5.3.0 add conditional add reference entity button to reference entities ( when add feature is enabled)
> feat: Bump molgenis-ui-form dep to 5.3.0

- packages/components-library/src/components/filters/containers/FilterContainer.vue
- Add prop to allow setting labels from outsize, this allows for runtime updates and i18n
> feat(components-library): Dynamic filter container labels

- packages/data-explorer/src/views/FiltersView.vue
- packages/data-explorer/yarn.lock
Allows filter container labels to be configured at runtime
> feat(data-explorer): Make filter container labels dynamic

- packages/data-explorer/src/repository/dataRepository.ts
- packages/data-explorer/src/types/ApiResponse.ts
- packages/data-explorer/tests/unit/mocks/rowDataSelfRef.ts
- packages/data-explorer/tests/unit/repository/dataRepository.spec.ts
Fix Data explorer v2 fails when trying to parse selfReference
- detect self reference and stop recursive parsing
Closes #556
> fix(data-explorer): Fix parsing self reference

- packages/security/src/components/GroupOverview.vue
> fix(security): Always show groups header

- packages/data-explorer/src/views/EntityView.vue
- packages/data-explorer/src/views/MainView.vue
- packages/data-explorer/tests/unit/components/dataView/DefaultCardContent.spec.ts
- packages/data-explorer/tests/unit/components/dataView/TableRow.spec.ts
- packages/data-explorer/tests/unit/views/EditDetailTemplate.spec.ts
- packages/data-explorer/tests/unit/views/EntityDetail.spec.ts
- packages/data-explorer/tests/unit/views/MainView.spec.ts
> fix: Let toast make room for shopping cart component

- packages/components-library/src/components/ui/Toaster.vue
- packages/data-explorer/tests/unit/components/dataView/DefaultCardContent.spec.ts
- packages/data-explorer/tests/unit/components/dataView/TableRow.spec.ts
- packages/data-explorer/tests/unit/views/EditDetailTemplate.spec.ts
- packages/data-explorer/tests/unit/views/EntityDetail.spec.ts
> fix: match the styles of different toasts

- packages/data-explorer/src/views/EditDetailTemplate.vue
- packages/data-explorer/tests/unit/components/dataView/DefaultCardContent.spec.ts
- packages/data-explorer/tests/unit/components/dataView/TableRow.spec.ts
- packages/data-explorer/tests/unit/views/EditDetailTemplate.spec.ts
- packages/data-explorer/tests/unit/views/EntityDetail.spec.ts
- packages/data-explorer/tests/unit/views/__snapshots__/EditDetailTemplate.spec.ts.snap
- Use style field component from forms lib
> feat(data-explorer): Use code mirror editor as template editor

- packages/data-explorer/src/views/EditDetailTemplate.vue
- packages/data-explorer/tests/unit/views/__snapshots__/EditDetailTemplate.spec.ts.snap
- packages/data-explorer/yarn.lock
> fix:(data-explorer): editor is now in landscape mode on small screens

- packages/searchall/package.json
- packages/searchall/src/components/EntityResult.vue
- packages/searchall/test/unit/specs/EntityResult.spec.js
- packages/searchall/yarn.lock
> fix(searchall): escape data explorer link

- packages/data-explorer/package.json
- packages/data-explorer/yarn.lock
- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
- packages/scripts/package.json
- packages/scripts/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
> feat: upgrade molgenis-ui-form to 5.3.1

- Jenkinsfile
> chore(Jenkinsfile): use fetch_codecov step

- packages/security/public/index.html
- packages/security/src/components/GroupDetail.vue
- packages/security/src/components/MemberAdd.vue
- packages/security/src/components/MemberDetail.vue
- packages/security/src/router/index.ts
- packages/security/src/store/actions.ts
- packages/security/src/store/helpers.ts
- packages/security/src/store/index.ts
- packages/security/src/store/mutations.ts
- packages/security/src/types/AddVOGroupMemberCommand.ts
- packages/security/src/types/Member.ts
- packages/security/src/types/SecurityModel.ts
- packages/security/src/types/VOGroup.ts
- packages/security/src/types/VOGroupMember.ts
- packages/security/tests/unit/components/GroupDetail.spec.ts
- packages/security/tests/unit/components/MemberAdd.spec.ts
- packages/security/tests/unit/components/MemberDetail.spec.ts
- packages/security/tests/unit/store/actions.spec.ts
- packages/security/tests/unit/store/mutations.spec.ts
- packages/security/vue.config.js
> feat(security): manage VO Group membership

- packages/data-explorer/src/routes.ts
> feat(data-explorer): Default view is now TableView

- packages/data-explorer/package.json
- packages/data-explorer/yarn.lock
- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
- packages/scripts/package.json
- packages/scripts/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
> fix: upgrade ui-forms to 5.4.1

- packages/data-explorer/src/store/explorer/actions.ts
- packages/data-explorer/src/store/explorer/mutations.ts
- packages/data-explorer/tests/unit/store/explorer/actions.spec.ts
fixes: https://github.com/molgenis/molgenis-frontend/issues/596
> fix(data-explorer): update count after removing row

- docker/proxy-config/proxy.d/frontend/custom.conf
- docker/proxy-config/proxy.d/frontend/experimental.conf
- docker/proxy-config/proxy.d/frontend/latest.conf
- docker/proxy-config/proxy.d/frontend/lts.conf
- docker/proxy-config/proxy.d/frontend/stable.conf
> chore: add proxy_ssl_server_name on;

- packages/metadata-manager/config/index.js
- packages/metadata-manager/package.json
- packages/metadata-manager/src/store/actions.js
chore(metadata-manager): updated config to make it easier to run against master-dev
> fix(metadata-manager): added correct attribute names for min & max

- packages/data-explorer/package.json
- packages/data-explorer/yarn.lock
- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
- packages/questionnaires/build/webpack.dev.conf.js
- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
- packages/scripts/package.json
- packages/scripts/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
> Release8.7/forms version bumps

- packages/one-click-importer/config/index.js
- packages/one-click-importer/src/store/actions.js
- packages/one-click-importer/test/unit/specs/store/actions.spec.js
- [NA] User documentation updated
- [NA ] Updated javascript typing
> fix(one-click-importer): response body was not parsed correctly

- docker/proxy-config/proxy.d/frontend/lts.conf
> fix: update docker config app versions

- packages/components-library/src/components/table/TableHeader.vue
- packages/components-library/src/components/table/TableRow.vue
- packages/components-library/src/components/table/dataDisplayTypes/DataDisplayCell.vue
- packages/components-library/src/components/table/dataDisplayTypes/DateDisplay.vue
- packages/components-library/src/components/table/dataDisplayTypes/EmailDisplay.vue
- packages/components-library/src/components/table/dataDisplayTypes/FileDisplay.vue
- packages/components-library/src/components/table/dataDisplayTypes/HTMLDisplay.vue
- packages/components-library/src/components/table/dataDisplayTypes/LinkDisplay.vue
- packages/components-library/src/components/table/dataDisplayTypes/RefDisplay.vue
- packages/components-library/src/components/table/dataDisplayTypes/RefTable.vue
- packages/components-library/src/components/table/dataDisplayTypes/StringDisplay.vue
- packages/components-library/src/dev-dependencies.ts
- packages/components-library/src/main.ts
- packages/components-library/styleguide.config.js
- packages/components-library/styleguidist-setup.js
- packages/data-explorer/src/components/dataView/TableRow.vue
Note: on merge also make it usable by merging: https://github.com/molgenis/molgenis-frontend/pull/625
> feat: add a table row and header component

- packages/components-library/src/components/table/TableRow.vue
- packages/components-library/src/components/table/dataDisplayTypes/RefTable.vue
fixed route-router naming error by not needing it in de components library at all
> fix: route-router naming issue

- Jenkinsfile
> chore: build styleguide preview

- Jenkinsfile
> chore: use namespace with pr instead of hash

- Jenkinsfile
> fix: master namespace

- packages/components-library/src/main.ts
> fix: forgot to add the component

- packages/components-library/src/components/filters/CheckboxFilter.vue
- packages/components-library/src/components/filters/MultiFilter.vue
> fix(components-library): add i18n functionality

- packages/components-library/src/components/blocks/SatisfyAll.vue
- packages/components-library/src/components/filters/CheckboxFilter.vue
- packages/components-library/src/components/filters/MultiFilter.vue
- packages/components-library/src/main.ts
- packages/components-library/styleguide.config.js
- packages/components-library/tests/unit/filters/CheckboxFilter.spec.ts
- packages/components-library/tests/unit/filters/MultiFilter.spec.ts
> fix(components-library): abstracted satisfy-all and changed it's styling

- packages/components-library/src/components/filters/MultiFilter.vue
> fix(components-library): don't use @ shortcut

- packages/components-library/.eslintrc.js
> fix(components-library): check if @ is used and error before it breaks master

- packages/components-library/README.md
- packages/components-library/src/components/blocks/SatisfyAllCheckbox.vue
- packages/components-library/src/components/filters/CheckboxFilter.vue
- packages/components-library/src/components/filters/MultiFilter.vue
- packages/components-library/src/main.ts
- packages/components-library/tests/unit/filters/CheckboxFilter.spec.ts
- packages/components-library/tests/unit/filters/MultiFilter.spec.ts
> fix(components-library): need name for SatisfyAllCheckbox for import to work

- packages/components-library/src/components/ui/Pagination.vue
- packages/components-library/tests/unit/ui/Pagination.spec.ts
Remove the data and listeners from Pagination.
Replace with computed model prop.
Add button classes and test them.
> fix(components-library): controlled Pagination

- docker/proxy-config/proxy.d/frontend/lts.conf
- docker/proxy-config/proxy.d/frontend/stable.conf
- packages/data-explorer/vue.config.js
- packages/data-explorer/yarn.lock
The config should also work for /@molgenis/expressions
and /@molgenis/molgenis-ui-form
> fix(docker): fix proxy conf

- packages/data-explorer/vue.config.js
- packages/data-explorer/yarn.lock
> chore(data-explorer): make e2e work again

- packages/metadata-manager/src/components/MetadataManagerAttributeEditForm.vue
fixes: https://github.com/molgenis/molgenis-frontend/issues/672
- [NA] Code unit/integration/system tested
- [NA] User documentation updated
- [NA] Updated javascript typing
> fix(metadata-manager): makes it able to clear some fields and still save

- packages/metadata-manager/package.json
- packages/metadata-manager/yarn.lock
fixes: https://github.com/molgenis/molgenis-frontend/issues/670
- [NA] Code unit/integration/system tested
- [NA] User documentation updated
- [?] No warnings during install
- [NA] Updated javascript typing
> fix: make tab key work with multiselect

- packages/core-ui/src/modules/react-components/AttributeControl.js
- packages/core-ui/src/modules/react-components/BoolControl.js
- packages/core-ui/src/modules/react-components/EntitySelectBox.js
- packages/core-ui/src/modules/react-components/Form.js
- packages/core-ui/src/modules/react-components/FormControl.js
- packages/core-ui/src/modules/react-components/FormControlGroup.js
- packages/core-ui/src/modules/react-components/Table.js
- packages/data-explorer/src/App.vue
- packages/data-explorer/src/components/DataRowEdit.vue
- packages/data-explorer/src/store/explorer/actions.ts
- packages/data-explorer/src/store/explorer/mutations.ts
- packages/data-explorer/src/store/explorer/state.ts
- packages/data-explorer/src/types/ApplicationState.ts
- packages/data-explorer/tests/unit/App.spec.ts
- packages/data-explorer/tests/unit/components/DataRowEdit.spec.ts
- packages/data-row-edit/public/index.html
- packages/data-row-edit/src/components/DataRowEdit.vue
- packages/data-row-edit/src/router/index.ts
- packages/data-row-edit/tests/unit/components/DataRowEdit.spec.ts
> feat: configure form options

- docker/proxy-config/proxy.d/frontend/lts.conf
- [NA] Code unit/integration/system tested
- [NA] User documentation updated
- [NA] Updated javascript typing
- [NA] Add to release notes
> fix(docker): 9.0 release lts version bumps

- packages/core-ui/src/modules/react-components/Table.js
> fix(core-ui): fixes the react forms not opening when creating a new row

- packages/components-library/src/components/filters/MultiFilter.vue
> fix: newValues was empty array, which was always truthy and led to error on join

- packages/components-library/src/components/filters/MultiFilter.vue
> fix: newValues not a vue data property

- packages/components-library/src/components/filters/MultiFilter.vue
> fix: list was not assigned again, so changes did not persist

- packages/components-library/src/components/filters/ActiveFilters.vue
- packages/components-library/src/components/filters/MultiFilter.vue
- packages/components-library/tests/unit/filters/MultiFilter.spec.ts
> fix: everything that could go wrong and has gone wrong, has been fixed

- docker/proxy-config/proxy.d/frontend/lts.conf
> fix: update lts.conf to latest versions

- README.md
- Functionality works & meets specifications
> doc: document how to add a plugin to molgenis

- docker/proxy-config/proxy.d/frontend/lts.conf
- docker/proxy-config/proxy.d/frontend/stable.conf
- packages/data-row-permissions/package.json
> fix: publicly release data-row-permissions plugin

- docker/proxy-config/proxy.d/frontend/lts.conf
- packages/data-row-permissions/package.json
> fix: namespace, and updated docker conf

- packages/data-row-permissions/src/components/ChangeOwnership.vue
> fix(data-row-permissions): add styling rules to fill the modal nicely with the selectlist

- packages/data-row-permissions/package.json
- packages/data-row-permissions/src/views/DataRowPermissions.vue
- packages/data-row-permissions/tests/unit/views/DataRowPermissions.spec.js
closes #704 
-  Add to release notes
> fix(data-row-permissions): if you change the id in url on DataRowPermissions screen, it actually works

- Jenkinsfile
> chore: moved e2e tests to their own stage, after preview, to speedup review process

- packages/components-library/src/components/filters/MultiFilter.vue
- packages/components-library/tests/unit/filters/MultiFilter.spec.ts
fix: finding no results now gives empty list. 
chore: Change cursor to help for warning badge
> fix: finding no results now gives empty list. Change cursor to help for warning badge

- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
> fix: versionbump of forms for the new fixes regarding the validation

- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
> fix: updated forms version for validation fixes

- docker/proxy-config/proxy.d/frontend/lts.conf
- Functionality works & meets specifications
> fix: redirect to latest molgenis-ui-form

- packages/app-manager/src/components/UpdateApp.vue
> fix: use app id to differ from other apps for update

- docker/proxy-config/proxy.d/frontend/lts.conf
> fix: bump app-manager so updating works with multiple apps present

- packages/data-explorer/package.json
- packages/data-explorer/yarn.lock
- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
> fix: upgrade molgenis-form version

- docker/proxy-config/proxy.d/frontend/lts.conf
- Functionality works & meets specifications
> Release/frontend 9.2.1

- packages/data-row-edit/src/components/DataRowEdit.vue
> feat: make cancel button red

- Jenkinsfile
> fix: refer to new namespace and release name

- packages/data-explorer/package.json
- packages/data-explorer/yarn.lock
- packages/data-row-edit/package.json
- packages/data-row-edit/yarn.lock
- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
- packages/settings/package.json
- packages/settings/yarn.lock
> fix: upgrade molgenis-ui-form dependencies to 5.9.1

- packages/data-explorer/package.json
- packages/data-row-edit/package.json
- packages/questionnaires/package.json
- packages/scripts/package.json
- packages/settings/package.json
> fix: version bump

- packages/data-explorer/yarn.lock
- packages/data-row-edit/yarn.lock
- packages/questionnaires/yarn.lock
- packages/scripts/yarn.lock
- packages/settings/yarn.lock
> fix: fix yarn lock files

- Jenkinsfile
- README.md
- docker/README.md
- packages/questionnaires/README.md
- packages/questionnaires/package.json
- packages/questionnaires/yarn.lock
> fix: make jenkins pipeline work again with new config

- Jenkinsfile
> fix: added concurrency to lerna build as well

- Jenkinsfile
> fix: removed sonar for now, until we have a new up-to-date container to run

- packages/questionnaires/src/components/ChapterForm.vue
make save on change work again by forcing a copy of fromdata (not a reference)
> fix: make save on change work again

- packages/questionnaires/src/components/ChapterForm.vue
- packages/questionnaires/src/store/actions.js
- Add fix/feature to [molgenis-frontend release draft](https://github.com/molgenis/molgenis-frontend/releases)
- Update package version in [molgenis-frontend release draft](https://github.com/molgenis/molgenis-frontend/releases)
> fix: try to get the questionnaires to work again
