Jenkinsfile

Due to concurrent builds, a new tag may have been created while we were building and testing.

chore(Jenkinsfile): re-fetch the tags before building the canary

---

README.md

Remove vue-bootstrap from 'guidelines' as it is an unneeded dependancies for most ui's and adds extra dependancies.

Remove vue-bootstrap from 'guidelines' as it is a unneeded dependancies

---

packages/core-ui/src/modules/react-components/Form.js

, even if value is null or undefined, still pass attribute.
Fix #15 
- This is needed because the evaluator now throws an error is expected attribute is missing.
- Change introduced in molgenis ref b24d9ad028f53462aeaa2248996bfc96c9b6e27d, evaluator.js api change attributes can no longer be null or undefined

Fix #15 Pass all form attrs to the evaluator

---

packages/data-row-edit/src/components/DataRowEdit.vue
packages/data-row-edit/src/repository/dataRowRepository.js
packages/data-row-edit/test/unit/specs/components/DataRowEdit.spec.js
packages/data-row-edit/test/unit/specs/repository/dataRowRepository.spec.js

Fix #8357
- Use i18n bool values when mapping entity
- Move mapping from repository to vue component to make use of i18n plugin and cleanup repository.
Note: new i18n values need to set in molgenis data-row-edit param files and loaded in the database.
related to: https://github.com/molgenis/molgenis/pull/8407

fix(data-row-edit): Fix 8356, use i18n bool values

---

packages/one-click-importer/src/components/OneClickImporter.vue

Set height of file input in one click importer to 100% to override the faulty bootstrap theme
calculation. We chose to keep the current file input rather than replace it by the bootstrap one
because we like the browser translations, those are lost when the bootstrap variant is used.
Fixes molgenis/molgenis#8368

fix(one-click-importer): Set height of file input to 100%

---

packages/security/src/store/actions.js

Fix #56: Cannot add group with name of subpackage

---

packages/security/src/store/actions.js
packages/security/test/unit/specs/store/actions.spec.js

Due to version guideline changes, public APIs no longer expose their version in the URL but they
should be requested via the content type.

[FIX] Remove version from identities endpoint URL

---

Jenkinsfile
copy_package_dist_dirs.sh
docker/Dockerfile
docker/docker-compose.yaml
docker/nginx-local.conf
packages/app-manager/config/index.js
packages/data-row-edit/config/index.js
packages/menu/vue.config.js
packages/menu/yarn.lock
packages/metadata-manager/config/index.js
packages/navigator/config/index.js
packages/one-click-importer/config/index.js
packages/questionnaires/config/index.js
packages/scripts/vue.config.js
packages/searchall/config/index.js
packages/security/config/index.js
packages/settings/config/index.js

Fixes the public paths of the production builds.
Resources can from now on be found on path `/@molgenis-ui/module/dist`.
Enables listing to the @molgenis-ui nginx.
Fixes #76 with a workaround. Ideally should be fixed on the cluster.

Fix public paths

---

docker/proxy-config/proxy.d/common.conf
docker/proxy-config/proxy.d/frontend/lts.conf

The unpkg resources with specific versions have long expiry dates.
If we get there using a fully versioned URL that is correct.
If we got there because we're following unpkg redirects it is incorrect.
The redirects may change.
If we get there because we've rewritten directly to a specific version
it is also incorrect. The proxy config may change.

chore(core-ui): cache proxy config for max 600s

---

packages/data-explorer/src/views/ClipboardView.vue
packages/data-explorer/tests/unit/views/ClipboardView.spec.ts

Load deep data when showing clipboard as refs may be part of row data

fix(data-explorer): load deep data when showing clipboard 

---

packages/questionnaires/src/store/actions.js
packages/questionnaires/test/unit/specs/store/actions.spec.js

We accidentally upgraded the api client which broke the message alerts.
Fixes #180

fix(questionnaires): handle error response

---

docker/proxy-config/proxy.d/frontend/lts.conf

- metadata-manager to 0.1.8 --> [CHANGELOG](https://github.com/molgenis/molgenis-frontend/blob/master/packages/metadata-manager/CHANGELOG.md)
- security-manager to 0.2.0 --> [CHANGELOG](https://github.com/molgenis/molgenis-frontend/blob/master/packages/security/CHANGELOG.md)
- legacy-lib to 1.1.2 --> [CHANGELOG](https://github.com/molgenis/molgenis-frontend/blob/master/packages/legacy-lib/CHANGELOG.md)

chore: bump app versions for backend version: 8.3.0

---

packages/data-explorer/src/repository/dataRepository.ts
packages/data-explorer/tests/unit/repository/dataRepository.spec.ts

Fix #275,  encodeRsql filter string before sending request
closes: #275

fix(data-explorer: Fix #275 encodeRsql filter string

---

packages/data-row-edit/src/repository/dataRowRepository.js
packages/data-row-edit/test/unit/specs/repository/dataRowRepository.spec.js

Closes #267
- check for file type in compounds

fix: #267 FILE datatype broken in new forms

---

README.md

Add a note in the Readme docs about linking the CI preview to a alternative backend

task: add alt backend to docs

---

packages/components-library/babel.config.js
packages/components-library/rollup.config.js

fix: distinguish vue-cli babel preset from rollup preset

---

packages/data-row-edit/package.json
packages/data-row-edit/src/components/DataRowEdit.vue
packages/data-row-edit/yarn.lock

Needed when compound includes reference types
Traverse attribute tree to flatten attributes before filtering ref-types and building map

fix(data-row-edit): recursively build reference map

---

packages/data-explorer/src/store/getters.ts
packages/data-explorer/src/types/ClipBoardItem.ts
packages/data-explorer/src/views/ClipboardView.vue
packages/data-explorer/src/views/DataView.vue
packages/data-explorer/tests/unit/store/getters.spec.ts
packages/data-explorer/tests/unit/views/ClipboardView.spec.ts
packages/data-explorer/tests/unit/views/DataView.spec.ts

fix(data-explorer): Fix selecting items with non standerd id / label
- Use metadata to find id and label columns
- Move finding id, and label and building clipboards items to getters for reuse
This closes #463, #462 

fix(data-explorer): Fix selecting items with non standerd id / label

---

packages/data-explorer/public/index.html
packages/data-explorer/tests/e2e/specs/test.js
packages/data-explorer/vue.config.js
packages/data-explorer/yarn.lock

BREAKING CHANGE: expects backend to serve active theme at '/theme/style.css'
Depends on: https://github.com/molgenis/molgenis/pull/9129

feat(data-explorer): Use '/theme/style.css' endpoint for styling

---

packages/data-explorer/src/components/dataView/TableRow.vue

- Set dataexplorer column max-width to more sensible default

fix(data-explorer): Bump table view column width

---

packages/data-explorer/src/views/MainView.vue

- Add missing check to showing description tooltip in case user in not signed in
- If the (optional) fields descrition is not set, no tooltip should be added

fix: Only show description if description is set

---

packages/data-explorer/package.json
packages/data-explorer/yarn.lock

- lerna  bump component lib version on component lib release ( but does not update the lock file)
- this data explorer should use 1.x version as pagination comp has breaking change

fix(data-explorer): set correct components lib version

---

packages/data-explorer/package.json
packages/data-explorer/yarn.lock

When is new version is released the ci bumps the version in the package json file,
but did not update the lockfile ( and version tags ).
Adding the postversion build test fixes theses issues ( new lockfile gets build)

fix(data-explorer): Fix issue with lock file

---

packages/data-explorer/src/components/ColumnSelection.vue
packages/data-explorer/src/store/mutations.ts
packages/data-explorer/src/views/MainView.vue
packages/data-explorer/tests/unit/components/ColumnSelection.spec.ts
packages/data-explorer/tests/unit/store/mutations.spec.ts

feat: routerstate can now be handled in one place, so we can also remove 'empty' filters from the url.

feat: routerstate can now be handled in one place

---

Jenkinsfile

chore: workaround for missing yarn.lock on lerna publish

---

packages/data-explorer/package.json
packages/data-explorer/yarn.lock

- lcov reporter stopped working because of handlebars issue
- version locking handlebars can be used as temp fix until vue cli release update with fix

chore(data-explorer): Fix issue with code cov

---

packages/data-explorer/src/store/actions.ts
packages/data-explorer/src/store/getters.ts
packages/data-explorer/src/store/mutations.ts
packages/data-explorer/src/store/state.ts
packages/data-explorer/src/types/ApplicationState.ts
packages/data-explorer/src/types/EntityTypeV2.ts
packages/data-explorer/src/views/MainView.vue
packages/data-explorer/src/views/ToolbarView.vue
packages/data-explorer/tests/unit/store/actions.spec.ts
packages/data-explorer/tests/unit/store/getters.spec.ts
packages/data-explorer/tests/unit/store/mutations.spec.ts
packages/data-explorer/tests/unit/views/ToolbarView.spec.ts

Use v2 api to fetch table permissons
Add/Edit buttons are show depending on table permissions
- [x ] Conventional commits (squash if needed)

feat(data-explorer): Fine grained table permissions

---

packages/data-explorer/src/lib/client.ts
packages/data-explorer/src/store/actions.ts
packages/data-explorer/tests/unit/lib/client.spec.ts

Closes #555
Remove the spinner when an error occurs 
Delete removing spinner in actions, no need to do this, this is handled by the caller

fix(data-explorer): Remove spinner on error

---

packages/data-explorer/src/components/dataView/DefaultCardContent.vue
packages/data-explorer/src/components/dataView/TableRow.vue
packages/data-explorer/src/views/EditDetailTemplate.vue
packages/data-explorer/src/views/EntityDetail.vue
packages/data-explorer/tests/unit/components/dataView/DefaultCardContent.spec.ts
packages/data-explorer/tests/unit/components/dataView/TableRow.spec.ts
packages/data-explorer/tests/unit/views/EditDetailTemplate.spec.ts
packages/data-explorer/tests/unit/views/EntityDetail.spec.ts

If a user has a active query and visits a details page, and then returns to the overview.
The query from the overview is used

fix(data-explorer): Use query if set

---

packages/metadata-manager/src/components/MetadataManagerContainer.vue
packages/metadata-manager/src/components/MetadataManagerEntityEditForm.vue

Default will be an auto id, which can be changed. Existing entity types will show the id but the input will be disabled.

feat(metadata-manager): add entity type id input

---

packages/core-ui/src/modules/react-components/Form.js

It was feeding a moment object, use iso string instead
Fixes #674
-  Add to release notes

fix(core-ui): string date value for expressions

---

packages/components-library/src/components/filters/MultiFilter.vue
packages/components-library/tests/unit/filters/MultiFilter.spec.ts

fix: when initialized with a value outside it's initial range, it is now retrieved and sorted on top, checked

fix: selection outside initial range not visible on mounted

---

packages/components-library/src/components/filters/MultiFilter.vue
packages/components-library/tests/unit/filters/MultiFilter.spec.ts

fix: multifilter now correctly emit selected values when searching and has return objects enabled
